// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nokuzckuqdmohbapruqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5va3V6Y2t1cWRtb2hiYXBydXFrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3NDc5MTksImV4cCI6MjA3MzMyMzkxOX0.Q2XzmQPXT9RgVodkNq-2D34ud45JWwYGbfITi32dJ9Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});